apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: slpcg84b4-nodejs
  janus-idp.io/tekton: slpcg84b4-nodejs
  backstage.io/kubernetes-id: slpcg84b4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: slpcg84b4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
